### ISSUE TITLE
Something not clear on DI Segues

### ISSUE THREAD

**Issue by mokagio** [Ashton-W/Ashton-W.github.io#16]
For the record http://www.ashton-w.net/2015/04/11/Dependency-Injection-Segues.html

Nice post, here's some feedback:
- I didn't get that the `destinationViewControllerConformingToProtocol` method used in the first protocol was defined by us until after I saw it's definition in the second protocol.
- What is the use case of `- (void)assignModel`
- When I read about Dependency Injection the spectrum is wider than just the model, how could you tackle those other dependencies, like database and network managers, framework objects like `NSUserDefaults`, etc?

:+1: for the example project... but it only has the first commit by GitHub :scream:

**Comment by Ashton-W** [comment]
I hope I've addressed these in the latest (last?) revision. Thanks Gio

**Comment by mokagio** [comment]
Yep, it's clearer now :+1:
