### ISSUE TITLE
Write about Breakpoints

### ISSUE THREAD

**Issue by Ashton-W** [Ashton-W/Ashton-W.github.io#2]

**Comment by Ashton-W** [comment]
Cover:
moving break points to 'user breakpoints' list.
Exception breakpoint
Unit Test Failure breakpoint
Symbolic breakpoint eg: Reveal
UIKit symbolic breakpoint

'Play sound' breakpoints
'Print' breakpoints

Conditional breakpoints?

**Comment by mokagio** [comment]
This would work well with a video

**Comment by Ashton-W** [comment]
Did a quick talk about this subject at @Odecee, need to write it down in blog format.
